### ISSUE TITLE
HTTP GET verb with a HTTP body?

### ISSUE THREAD

**Issue by cdhit** [Money-Manager-SaaS/mmss-frontend#37]
Not sure if this is possible? Discuss 

https://github.com/Money-Manager-SaaS/mmss-frontend/blob/ffc50349cb9404c840bff31a3b9059a3c6350f6d/src/api/index.js#L22

@kekakuka @tim-hub

**Comment by tim-hub** [comment]
not sure, I think get request has no body

**Comment by cdhit** [comment]
@kekakuka confirmed axios can convert the into query parameter.
@tim-hub
